/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Employee.Payroll.JDBC;

import org.junit.Test;

import Employee.Payroll.JDBC.EmployeePayrollService.IOService;
import junit.framework.Assert;

import static org.junit.Assert.*;

import java.util.List;

public class EmployeePayrollJDBCTest {
    @Test
    public void givenEmpPayrollDataInDB_ShouldMatchEmpCount() {
    	EmployeePayrollService empPayrollService = new EmployeePayrollService();
    	List<EmployeePayrollData> empPayrollData = empPayrollService.readEmployeePayrollData(IOService.DB_IO);
    	Assert.assertEquals(3, empPayrollData.size());
    }
    
    @Test 
    public void givenNewSalary_WhenUpdated_shouldMatchWithDB() {
    	EmployeePayrollService empPayrollService = new EmployeePayrollService();
    	List<EmployeePayrollData> empPayrollData = empPayrollService.readEmployeePayrollData(IOService.DB_IO);
    	empPayrollService.updateEmployeeSalary("Soumik", 70000);
    	boolean result = empPayrollService.checkEmployeePayrollInSyncWithDB("Soumik");
    	Assert.assertTrue(result);
    }
}
