/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Employee.Payroll.JDBC;

import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;

public class EmployeePayrollJDBC {
	private Connection getConnection() throws SQLException {
		String jdbcURL = "jdbc:mysql://localhost:3306/employee?useSSL=false";
		String userName = "root";
		String password = "Resurrection@5";
		Connection connection;
		connection = DriverManager.getConnection(jdbcURL, userName, password);
		return connection;
	}

	public List<EmployeePayrollData> readData() {
		String sql = "SELECT * FROM emp_payroll ; ";
		List<EmployeePayrollData> empPayrollList = new ArrayList<>();
		try {
			Connection connection = this.getConnection();
			Statement statement = connection.createStatement();
			ResultSet result = statement.executeQuery(sql);
			while(result.next()) {
				int id = result.getInt("id");
				String name = result.getString("name");
				double salary = result.getDouble("salary");
				String gender = result.getString("gender");
				LocalDate start = result.getDate("start").toLocalDate();
				empPayrollList.add(new EmployeePayrollData(id,name,salary,start));
			}
		}
		catch(SQLException e) {
			e.printStackTrace();
		}
		return empPayrollList;
	}
	
}
