/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Employee.Payroll.JDBC;

import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.util.Enumeration;

public class EmployeePayrollJDBC {
	public static void main(String[] args) {
		String jdbcUrl = "jdbc:mysql://localhost:3306/payroll_service?useSSL=false";
    	String userName = "root";
    	String password = "Resurrection@5";
    	
    	Connection connection;
    	try {
    		Class.forName("com.mysql.jdbc.Driver");
    		System.out.println("Driver loaded!");
    	}
    	catch(ClassNotFoundException e) {
    		throw new IllegalStateException("Cannot find driver in the classpath", e);
    	}
    	listDrivers();
    	try {
    		System.out.println("COnnecting to database : " + jdbcUrl);
    		connection = DriverManager.getConnection(jdbcUrl, userName, password);
    		System.out.println("Connection is successful!    "  + connection);
    	}
    	catch(Exception e) {
    		e.printStackTrace();
    	}
	}
	
	private static void listDrivers() {
		Enumeration<Driver> driverList = DriverManager.getDrivers();
		while(driverList.hasMoreElements()) {
			Driver driverClass = (Driver)driverList.nextElement();
			System.out.println("    " + driverClass.getClass().getName());
		}
	}
}
